spring:
  datasource:
    url: jdbc:h2:file:./data/demo
  jpa:
    hibernate:
      ddl-auto: update

app:
  noteEvents: file:pathToNoteEvents.csv
  metamap:
    ports: 8066,8067,8068,8069,8070,8071

