spring:
  datasource:
    url: jdbc:h2:file:./data/demo
  jpa:
    hibernate:
      ddl-auto: update
  task:
    execution:
      pool:
        core-size: 8
        max-size: 8
      shutdown:
        await-termination: true
      thread-name-prefix: aluna-task-

app:
  noteEvents: file:/home/ubuntu/noteevents.csv
  subjectIds: file:/home/ubuntu/subject_id
  metamap:
    ports: 8066,8067,8068,8069,8070,8071

